name: push project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: Run lints
        run: npm lint
      - name: Run tests
        run: npm test
      - name: Run builds
        run: npm build